const zonesVacationData = [
//   {
//     link: "/vacances/rentree-scolaire/",
//     title: "Rentrée scolaire 2024",
//     startDate: null,
//     endDate: null,
//     zoneA: "Zone A",
//     zoneB: "Zone B",
//     zoneC: "Zone C",
//     zoneCorse: "Corse",
//     zoneGuadeloupe: "Guadeloupe",
//     zoneGuyane: "Guyane",
//     zoneMartinique: "Martinique",
//     zoneMayotte: "Mayotte",
//     zoneRéunion: "Réunion",
//   },
  {
    link: "/vacances/vacances-de-la-toussaint/",
    title: "Vacances de la Toussaint",
    startDate: "samedi 13 octobre 2024",
    endDate: null,
    zoneA: "Zone A",
    zoneB: "Zone B",
    zoneC: "Zone C",
    zoneCorse: "Corse",
    zoneGuadeloupe: "Guadeloupe",
    zoneGuyane: "Guyane",
    zoneMartinique: "Martinique",
    zoneMayotte: "Mayotte",
    zoneRéunion: "Réunion",
  },
  {
    link: "/vacances/vacances-de-noel/",
    title: "Vacances de Noël",
    startDate: "samedi 30 décembre 2024",
    endDate: null,
    zoneA: "Zone A",
    zoneB: "Zone B",
    zoneC: "Zone C",
    zoneCorse: "Corse",
    zoneGuadeloupe: "Guadeloupe",
    zoneGuyane: "Guyane",
    zoneMartinique: "Martinique",
    zoneMayotte: "Mayotte",
    zoneRéunion: "Réunion",
  },
  {
    link: "/vacances/vacances-d-hiver-vacances-de-fevrier/",
    title: "Vacances d'hiver",
    startDate: "samedi 02 février 2025",
    endDate: null,
    zoneA: "Zone A",
    zoneB: "Zone B",
    zoneC: "Zone C",
    zoneCorse: "Corse",
    zoneGuadeloupe: "Guadeloupe",
    zoneGuyane: "Guyane",
    zoneMartinique: "Martinique",
    zoneMayotte: "Mayotte",
    zoneRéunion: "Réunion",
  },
  {
    link: "/vacances/vacances-de-printemps-vacances-de-paques/",
    title: "Vacances de printemps",
    startDate: "samedi 19 avril 2025",
    endDate: null,
    zoneA: "Zone A",
    zoneB: "Zone B",
    zoneC: "Zone C",
    zoneCorse: "Corse",
    zoneGuadeloupe: "Guadeloupe",
    zoneGuyane: "Guyane",
    zoneMartinique: "Martinique",
    zoneMayotte: "Mayotte",
    zoneRéunion: "Réunion",
  },
  {
    link: "/vacances/ascension/",
    title: "Pont de l'Ascension",
    startDate: "mercredi 28 mai 2025",
    endDate: null,
    zoneA: "Zone A",
    zoneB: "Zone B",
    zoneC: "Zone C",
    zoneCorse: "Corse",
    zoneGuadeloupe: "Guadeloupe",
    zoneGuyane: "Guyane",
    zoneMartinique: "Martinique",
    zoneMayotte: "Mayotte",
    zoneRéunion: "Réunion",
  },
  {
    link: "/vacances/grandes-vacances/",
    title: "Grandes Vacances",
    startDate: "samedi 5 juillet 2025",
    endDate: null,
    zoneA: "Zone A",
    zoneB: "Zone B",
    zoneC: "Zone C",
    zoneCorse: "Corse",
    zoneGuadeloupe: "Guadeloupe",
    zoneGuyane: "Guyane",
    zoneMartinique: "Martinique",
    zoneMayotte: "Mayotte",
    zoneRéunion: "Réunion",
  },
];

module.exports = {
  zonesVacationData,
};
